### ISSUE TITLE
Issue with performing relative imports

### ISSUE THREAD

**Issue by localhuman** [CityOfZion/neo-boa#18]
Some users report issues with compiling files that import other modules.
For example: 
```
>>> from boa.compiler import Compiler
>>> Compiler.load_and_save('../neo-ico-template/ico_template.py')
LOADING AND SAVING! ../neo-ico-template/ico_template.py 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/whale/blockchain/neo-python/neo-python/venv/lib/python3.5/site-packages/boa/compiler.py", line 106, in load_and_save
    compiler = Compiler.load(path)
  File "/Users/whale/blockchain/neo-python/neo-python/venv/lib/python3.5/site-packages/boa/compiler.py", line 139, in load
    module = Module(path)
  File "/Users/whale/blockchain/neo-python/neo-python/venv/lib/python3.5/site-packages/boa/code/module.py", line 237, in __init__
    self.build()
  File "/Users/whale/blockchain/neo-python/neo-python/venv/lib/python3.5/site-packages/boa/code/module.py", line 261, in build
    imp = Import(lineset.items, self.path)
  File "/Users/whale/blockchain/neo-python/neo-python/venv/lib/python3.5/site-packages/boa/code/items.py", line 228, in __init__
    self.build()
  File "/Users/whale/blockchain/neo-python/neo-python/venv/lib/python3.5/site-packages/boa/code/items.py", line 237, in build
    module = importlib.import_module(self.module_path, self.module_path)
  File "/Users/whale/.pyenv/versions/3.5.1/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 981, in _gcd_import
  File "<frozen importlib._bootstrap>", line 931, in _sanity_check
SystemError: Parent module 'boa.blockchain.vm.Neo.Runtime' not loaded, cannot perform relative import
```

The compiler should do the best it can do determine relevant paths and add them to sys.path when necessary.

**Comment by WhaleChen** [comment]
yes!  My system is Mac OS X EI Captain version 10.11.6.
- python 3.5.1 
- neo-boa 0.2.0 
- requirements.txt installed 
```
SystemError: Parent module 'boa.blockchain.vm.Neo.Runtime' not loaded, cannot perform relative import```
I do not understand why cannot perform relative import and how to do absolute import instead~ Many Thx!

**Comment by localhuman** [comment]
Ok, just tried to reproduce. It looks like you're using `pyenv` ? I think that may be causing the issue.

**Comment by localhuman** [comment]
Seems like `pyenv` could mess with paths, especially in regards to `virtualenvironments`.  https://github.com/pyenv/pyenv#managing-virtual-environments

**Comment by WhaleChen** [comment]
```
(venv) whaledeMBP:neo-python whale$ python3
Python 3.5.4 (v3.5.4:3f56838976, Aug  7 2017, 12:56:33) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from boa.compiler import Compiler
>>> Compiler.load_and_save('./neo-ico-template/ico_template.py')
LOADING AND SAVING! ./neo-ico-template/ico_template.py 
Trimming load self method
```
@localhuman Thx!!! Done. The problem is caused by ```pyenv``` ~ Many thx~

**Comment by kilimchoi** [comment]
@WhaleChen I'm hitting the same issue. Would you mind explaining how you resolved it?
