### ISSUE TITLE
Compiler Exception: Target method 2 not found

### ISSUE THREAD

**Issue by jordanfung** [CityOfZion/neo-boa#19]
my code looks like this:

```
def func(a, b):
    return a + b

def Main():
    return func(func(1, 2), 3)
```

and the compiler said:
```
Traceback (most recent call last):
  File "./neopy", line 6, in <module>
    Compiler.load_and_save(i)
  File "/Users/foo/.pyenv/versions/3.5.4/lib/python3.5/site-packages/neo_boa-0.2.1-py3.5.egg/boa/compiler.py", line 105, in load_and_save
    data = compiler.write()
  File "/Users/foo/.pyenv/versions/3.5.4/lib/python3.5/site-packages/neo_boa-0.2.1-py3.5.egg/boa/compiler.py", line 81, in write
    out_bytes = bytes(module.write())
  File "/Users/foo/.pyenv/versions/3.5.4/lib/python3.5/site-packages/neo_boa-0.2.1-py3.5.egg/boa/code/module.py", line 403, in write
    self.link_methods()
  File "/Users/foo/.pyenv/versions/3.5.4/lib/python3.5/site-packages/neo_boa-0.2.1-py3.5.egg/boa/code/module.py", line 462, in link_methods
    raise Exception("Target method %s not found" % vmtoken.target_method)
Exception: Target method 2 not found

```

**Comment by localhuman** [comment]
because of VM and compiler limitations, calling a method from within a method call is not supported.  To get a good idea of everything that has been tested and working, look at the samples here:
https://github.com/CityOfZion/neo-boa/tree/master/boa/tests/src
