### ISSUE TITLE
failed to compile python file with smart contract to avm file

### ISSUE THREAD

**Issue by blockchain1977** [CityOfZion/neo-boa#46]
Following guide, I installed python 3.5.2 and boa. I got below error when trying to compile to avm file.
AttributeError: module 'sys' has no attribute '__file__'

Detial error message as below: 
(venv) ubuntu@ubuntu-VirtualBox:~/Downloads/neo-python-master/venv$ python boafile.py
Traceback (most recent call last):
  File "boafile.py", line 3, in <module>
    Compiler.load_and_save('/home/ubuntu/Downloads/neo-python-master/venv/test.py')
  File "/home/ubuntu/Downloads/neo-python-master/venv/lib/python3.5/site-packages/boa/compiler.py", line 104, in load_and_save
    compiler = Compiler.load(path)
  File "/home/ubuntu/Downloads/neo-python-master/venv/lib/python3.5/site-packages/boa/compiler.py", line 137, in load
    module = Module(path)
  File "/home/ubuntu/Downloads/neo-python-master/venv/lib/python3.5/site-packages/boa/code/module.py", line 235, in __init__
    self.build()
  File "/home/ubuntu/Downloads/neo-python-master/venv/lib/python3.5/site-packages/boa/code/module.py", line 259, in build
    imp = Import(lineset.items, self.path)
  File "/home/ubuntu/Downloads/neo-python-master/venv/lib/python3.5/site-packages/boa/code/items.py", line 220, in __init__
    self.build()
  File "/home/ubuntu/Downloads/neo-python-master/venv/lib/python3.5/site-packages/boa/code/items.py", line 239, in build
    items_to_import=self.module_items_to_import)
  File "/home/ubuntu/Downloads/neo-python-master/venv/lib/python3.5/site-packages/boa/code/module.py", line 235, in __init__
    self.build()
  File "/home/ubuntu/Downloads/neo-python-master/venv/lib/python3.5/site-packages/boa/code/module.py", line 259, in build
    imp = Import(lineset.items, self.path)
  File "/home/ubuntu/Downloads/neo-python-master/venv/lib/python3.5/site-packages/boa/code/items.py", line 220, in __init__
    self.build()
  File "/home/ubuntu/Downloads/neo-python-master/venv/lib/python3.5/site-packages/boa/code/items.py", line 231, in build
    filename = module.__file__
AttributeError: module 'sys' has no attribute '__file__'

I modified items.py source code. Change the "module.__file__' as the file path that I want to compile. Then, I got below error: 
RecursionError: maximum recursion depth exceeded

Detail error as below:
    self.build()
  File "/home/ubuntu/Downloads/neo-python-master/venv/lib/python3.5/site-packages/boa/code/items.py", line 239, in build
    items_to_import=self.module_items_to_import)
  File "/home/ubuntu/Downloads/neo-python-master/venv/lib/python3.5/site-packages/boa/code/module.py", line 235, in __init__
    self.build()
  File "/home/ubuntu/Downloads/neo-python-master/venv/lib/python3.5/site-packages/boa/code/module.py", line 259, in build
    imp = Import(lineset.items, self.path)
  File "/home/ubuntu/Downloads/neo-python-master/venv/lib/python3.5/site-packages/boa/code/items.py", line 220, in __init__
    self.build()
  File "/home/ubuntu/Downloads/neo-python-master/venv/lib/python3.5/site-packages/boa/code/items.py", line 229, in build
    module = importlib.import_module(self.module_path, self.module_path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 993, in _gcd_import
  File "<frozen importlib._bootstrap>", line 202, in _lock_unlock_module
  File "<frozen importlib._bootstrap>", line 189, in _get_module_lock
RecursionError: maximum recursion depth exceeded

**Comment by localhuman** [comment]
are you trying to import `sys` module? If so you can't do that.

**Comment by blockchain1977** [comment]
I'm trying to compile the example smart-contract.py:

I created a file "boafile.py" with below content:
from boa.compiler import Compiler
Compiler.load_and_save('./smart-contract.py')

Then, I ran command : python boafile.py

I was expecting the smart-contract.avm file generated. But got the error "AttributeError: module 'sys' has no attribute 'file'"

**Comment by PJUllrich** [comment]
I face the same problem whenever I include the `neo` or `logzero` framework with e.g. `from logzero import logger`. Haven't tried it with other frameworks, but if I uncomment these import (and simply don't use these libaries), it compiles fine. But this does not seem like a feasible workaround.

**Comment by metachris** [comment]
You cannot import external Python modules into smart contracts. It just supports modules that strictly comply with the supported functionality of neo-boa.

**Comment by PJUllrich** [comment]
So, one cannot use libraries like `logzero` and `neo` as described in the `neo-python` project? (e.g. [here](https://neo-python.readthedocs.io/en/latest/settings-and-logging.html))

**Comment by localhuman** [comment]
There is documentation specific to the compiler here:
https://neo-boa.readthedocs.io/en/latest/

**Comment by blockchain1977** [comment]
Thanks everyone for your help!

@PJUllrich , I commented out some imports, the error messages are different. It complaining that some other components has no attribute '__file__'. It seems on the right track. I will investigate deeper. Thanks!

@localhuman , I did have investigated the documentation you provided before I submit this issue. While, I didn't find a solution. And the smart contract I used is the one provided in neo-python-master/examples/smart-contract.py. The only thing I did is that :
    I created a file "boafile.py" with below content:
    from boa.compiler import Compiler
    Compiler.load_and_save('./smart-contract.py')

    Then, I ran command : python boafile.py

BTW: So for late response. I am in New Zealand. And now, it's 9:44 AM.

**Comment by localhuman** [comment]
after you run `Compiler.load_and_save('./smart-contract.py)` you'll now have a file with an extension of `.avm`.

In `neo-python` or Neo GUI you can load that `.avm` file in to actually work with it, ie `import contract /path/to/.avm {params} {return_type} {needs_storage} {needs_dynamic_invoke}`

**Comment by blockchain1977** [comment]
The problem is that, the .avm file was not generated... It's casued by the error of module 'sys' has no attribute '__file__'.
I commented out some 'unnecessary' imports from smart-contract.py, but still see various error like above.
