### ISSUE TITLE
Tests fail when run multiple times

### ISSUE THREAD

**Issue by brianlenz** [CityOfZion/neo-boa#60]
If you run `make test` multiple consecutive times for neo-python, the neo_boa tests will fail for `test_ico_template.py` with 5 different errors:

```
======================================================================
FAIL: test_ICOTemplate_1 (boa_test.tests.test_ico_template.TestContract)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/brian/Projects/Narrative/neo-python/venv/lib/python3.6/site-packages/boa_test/tests/test_ico_template.py", line 70, in test_ICOTemplate_1
    self.assertEqual(results[0].GetBigInteger(), 0)
AssertionError: 250040000000000 != 0

======================================================================
FAIL: test_ICOTemplate_2 (boa_test.tests.test_ico_template.TestContract)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/brian/Projects/Narrative/neo-python/venv/lib/python3.6/site-packages/boa_test/tests/test_ico_template.py", line 124, in test_ICOTemplate_2
    self.assertEqual(results[0].GetBigInteger(), test_transfer_amount)
AssertionError: 7200010003 != 2400000001

======================================================================
FAIL: test_ICOTemplate_3_KYC (boa_test.tests.test_ico_template.TestContract)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/brian/Projects/Narrative/neo-python/venv/lib/python3.6/site-packages/boa_test/tests/test_ico_template.py", line 178, in test_ICOTemplate_3_KYC
    self.assertEqual(results[0].GetBoolean(), False)
AssertionError: True != False

======================================================================
FAIL: test_ICOTemplate_5_mint (boa_test.tests.test_ico_template.TestContract)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/brian/Projects/Narrative/neo-python/venv/lib/python3.6/site-packages/boa_test/tests/test_ico_template.py", line 252, in test_ICOTemplate_5_mint
    self.assertEqual(results[0].GetBoolean(), True)
AssertionError: False != True

======================================================================
FAIL: test_ICOTemplate_6_approval (boa_test.tests.test_ico_template.TestContract)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/brian/Projects/Narrative/neo-python/venv/lib/python3.6/site-packages/boa_test/tests/test_ico_template.py", line 284, in test_ICOTemplate_6_approval
    self.assertEqual(results[0].GetBigInteger(), 0)
AssertionError: 123234 != 0

----------------------------------------------------------------------
Ran 73 tests in 36.524s

FAILED (failures=5)
make: *** [test] Error 1
```

The issue is that the `fixtures/debugstorage` dir isn't being removed properly. I've confirmed this is the case by checking the `fixtures` dir after running `make test` and the `debugstorage` dir is always left behind. If I delete it and then run `make test`, it will succeed.

There is code that attempts to do it:

https://github.com/CityOfZion/neo-boa/blob/master/boa_test/tests/test_ico_template.py#L30

But it's not working for some reason. The same code (and issue?) exists in `test_storage.py` and `test_contract.py`, as well. Do these tests need to be updated to override `leveldb_testpath()`?

I'm not 100% sure on the solution, so I've not submitted a PR.

One related aside: it looks like the `btest.tar.gz` file is left around after running the tests, too. This doesn't seem to be causing any issues, but perhaps we should delete it for completeness, as well?

@localhuman, any thoughts?

**Comment by localhuman** [comment]
This cleans up debug storage after tests have been run:
https://github.com/CityOfZion/neo-boa/blob/master/boa_test/tests/test_storage.py#L16

**Comment by brianlenz** [comment]
Yeah, I linked to that in one of the other tests. It's not working 😁 (at least not when run via neo-python)

**Comment by brianlenz** [comment]
Confirmed it's working now 👍
