### ISSUE TITLE
negative shift count error when running unit test

### ISSUE THREAD

**Issue by jhwinter** [CityOfZion/neo-boa#92]
I get a "negative shift count error" when running the unit tests. Is this supposed to happen?
```
python -m unittest discover boa_test

[E 180919 14:03:31 ExecutionEngine:947] COULD NOT EXECUTE OP (63): negative shift count b'\x98' SHL
[E 180919 14:03:31 ExecutionEngine:948] negative shift count
    Traceback (most recent call last):
      File "/Users/jonathan/.pyenv/versions/3.6.6/envs/venv-neo-boa/lib/python3.6/site-packages/neo/VM/ExecutionEngine.py", line 939, in StepInto
        self.ExecuteOp(op, self.CurrentContext)
      File "/Users/jonathan/.pyenv/versions/3.6.6/envs/venv-neo-boa/lib/python3.6/site-packages/neo/VM/ExecutionEngine.py", line 485, in ExecuteOp
        estack.PushT(x << n)
    ValueError: negative shift count
[I 180919 14:03:31 Invoke:586] Used 0.049 Gas 
[I 180919 14:03:31 Invoke:586] Used 0.049 Gas 
[I 180919 14:03:31 Invoke:586] Used 0.053 Gas 
[I 180919 14:03:31 Invoke:586] Used 0.053 Gas 
[I 180919 14:03:31 Invoke:586] Used 0.057 Gas 
[I 180919 14:03:31 Invoke:586] Used 0.057 Gas 
[I 180919 14:03:31 Invoke:586] Used 0.061 Gas 
[I 180919 14:03:31 Invoke:586] Used 0.063 Gas 
[I 180919 14:03:31 Invoke:586] Used 0.063 Gas 
.[I 180919 14:03:40 LevelDBBlockchain:114] Created Blockchain DB at /Users/jonathan/.neopython/fixtures/test_chain 
```

**Comment by localhuman** [comment]
Yes.
